#!/usr/bin/env bash

cp -rf repo/.pyup.yml .
cp -rf repo/.travis.yml /Users/rlaney/Projects/cookiecutter-django/.travis.yml
cp -rf repo/CONTRIBUTORS.rst /Users/rlaney/Projects/cookiecutter-django/CONTRIBUTORS.rst
cp -rf repo/README.rst /Users/rlaney/Projects/cookiecutter-django/README.rst
cp -rf repo/cookiecutter.json /Users/rlaney/Projects/cookiecutter-django/cookiecutter.json
cp -rf repo/docs/deployment-on-heroku.rst /Users/rlaney/Projects/cookiecutter-django/docs/deployment-on-heroku.rst
cp -rf repo/docs/deployment-with-docker.rst /Users/rlaney/Projects/cookiecutter-django/docs/deployment-with-docker.rst
cp -rf repo/docs/developing-locally-docker.rst /Users/rlaney/Projects/cookiecutter-django/docs/developing-locally-docker.rst
cp -rf repo/docs/developing-locally.rst /Users/rlaney/Projects/cookiecutter-django/docs/developing-locally.rst
cp -rf repo/docs/docker-postgres-backups.rst /Users/rlaney/Projects/cookiecutter-django/docs/docker-postgres-backups.rst
cp -rf repo/docs/linters.rst /Users/rlaney/Projects/cookiecutter-django/docs/linters.rst
cp -rf repo/docs/project-generation-options.rst /Users/rlaney/Projects/cookiecutter-django/docs/project-generation-options.rst
cp -rf repo/docs/settings.rst /Users/rlaney/Projects/cookiecutter-django/docs/settings.rst
cp -rf repo/docs/troubleshooting.rst /Users/rlaney/Projects/cookiecutter-django/docs/troubleshooting.rst
cp -rf repo/hooks/post_gen_project.py /Users/rlaney/Projects/cookiecutter-django/hooks/post_gen_project.py
cp -rf repo/hooks/pre_gen_project.py /Users/rlaney/Projects/cookiecutter-django/hooks/pre_gen_project.py
cp -rf repo/requirements.txt /Users/rlaney/Projects/cookiecutter-django/requirements.txt
cp -rf repo/setup.py /Users/rlaney/Projects/cookiecutter-django/setup.py
cp -rf repo/tests/test_cookiecutter_generation.py /Users/rlaney/Projects/cookiecutter-django/tests/test_cookiecutter_generation.py
cp -rf repo/tests/test_docker.sh /Users/rlaney/Projects/cookiecutter-django/tests/test_docker.sh
cp -rf repo/tox.ini /Users/rlaney/Projects/cookiecutter-django/tox.ini
cp -rf repo/{{cookiecutter.project_slug}}/.envs/.production/.django /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/.envs/.production/.django
cp -rf repo/{{cookiecutter.project_slug}}/.pylintrc /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/.pylintrc
cp -rf repo/{{cookiecutter.project_slug}}/.travis.yml /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/.travis.yml
cp -rf repo/{{cookiecutter.project_slug}}/README.rst /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/README.rst
cp -rf repo/{{cookiecutter.project_slug}}/compose/local/django/Dockerfile /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/compose/local/django/Dockerfile
cp -rf repo/{{cookiecutter.project_slug}}/compose/production/django/Dockerfile /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/compose/production/django/Dockerfile
cp -rf repo/{{cookiecutter.project_slug}}/config/settings/base.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/config/settings/base.py
cp -rf repo/{{cookiecutter.project_slug}}/config/settings/local.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/config/settings/local.py
cp -rf repo/{{cookiecutter.project_slug}}/config/settings/production.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/config/settings/production.py
cp -rf repo/{{cookiecutter.project_slug}}/config/settings/test.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/config/settings/test.py
cp -rf repo/{{cookiecutter.project_slug}}/config/urls.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/config/urls.py
cp -rf repo/{{cookiecutter.project_slug}}/config/wsgi.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/config/wsgi.py
cp -rf repo/{{cookiecutter.project_slug}}/gulpfile.js /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/gulpfile.js
cp -rf repo/{{cookiecutter.project_slug}}/local.yml /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/local.yml
cp -rf repo/{{cookiecutter.project_slug}}/merge_production_dotenvs_in_dotenv.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/merge_production_dotenvs_in_dotenv.py
cp -rf repo/{{cookiecutter.project_slug}}/package.json /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/package.json
cp -rf repo/{{cookiecutter.project_slug}}/production.yml /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/production.yml
cp -rf repo/{{cookiecutter.project_slug}}/requirements/base.txt /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/requirements/base.txt
cp -rf repo/{{cookiecutter.project_slug}}/requirements/local.txt /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/requirements/local.txt
cp -rf repo/{{cookiecutter.project_slug}}/requirements/production.txt /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/requirements/production.txt
cp -rf repo/{{cookiecutter.project_slug}}/runtime.txt /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/runtime.txt
cp -rf repo/{{cookiecutter.project_slug}}/setup.cfg /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/setup.cfg
cp -rf repo/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/taskapp/celery.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/taskapp/celery.py
cp -rf repo/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/base.html /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/templates/base.html
cp -rf repo/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/adapters.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/adapters.py
cp -rf repo/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/forms.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/forms.py
cp -rf repo/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/tests/factories.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/tests/factories.py
cp -rf repo/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/tests/test_forms.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/tests/test_forms.py
cp -rf repo/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/tests/test_views.py /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/users/tests/test_views.py

cp -rf repo/docs/mailgun.rst docs/mailgun.rst
cp -rf repo/{{cookiecutter.project_slug}}/compose/local/node {{cookiecutter.project_slug}}/compose/local/node
cp -rf repo/{{cookiecutter.project_slug}}/compose/production/aws {{cookiecutter.project_slug}}/compose/production/aws
cp -rf repo/{{cookiecutter.project_slug}}/compose/production/traefik {{cookiecutter.project_slug}}/compose/production/traefik
cp -rf repo/{{cookiecutter.project_slug}}/utility/requirements-bionic.apt {{cookiecutter.project_slug}}/utility/requirements-bionic.apt

cp -rf /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/docs/deploy.rst         /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/docs/old_deploy.rst
cp -rf /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/docs/docker_ec2.rst     /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/docs/old_docker_ec2.rst
cp -rf /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/docs/install.rst        /Users/rlaney/Projects/cookiecutter-django/{{cookiecutter.project_slug}}/docs/old_install.rst
